name: shopzy
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'


#-----------------PACKAGES-----------------#
dependencies:
  flutter:
    sdk: flutter

  # Utility Packages
  http: ^1.1.0
  intl: ^0.18.1
  logger: ^2.0.1
  url_launcher: ^6.1.12
  flutter_native_splash: ^2.4.0
  smooth_page_indicator: ^1.1.0

  # icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.6

  # state management:
  get: ^4.6.6
  get_storage: ^2.1.1

  # Product Specific


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

#----------------LOCAL ASSETS--------------------#
  assets:
    - assets/fonts/
    - assets/icons/brands/
    - assets/logos/
    - assets/images/on_boarding_images/


  #----------------LOCAL FONTS--------------------#
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-BoldItalic.ttf
#        - asset: assets/fonts/Poppins-ExtraBold.ttf
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
#        - asset: assets/fonts/Poppins-Thin.ttf




  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
